on:
  fork:
  push:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]
  pull_request:
    types: [closed]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # This GitHub action uses the action from EddieHubCommunity/gh-action-community, Thanks for Eddie
      - uses: EddieHubCommunity/gh-action-community/src/welcome@v0.3 
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project</h1> Thank you for raising an <strong>Issue</strong>, Welcome to <strong>Project Guidance</strong>'
          pr-message: '<h1>It''s great having you contribute to this project</h1> Thank you for opening a <strong>Pull Request</strong>, Welcome to <strong>Project Guidance</strong>'
          footer: 'We will review everything and get back to you, Please checkout our <a href="https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md">CONTRIBUTING RULES</a> and <a href="https://github.com/Kushal997-das/Project-Guidance/blob/main/CODE_OF_CONDUCT.md">CODE OF CONDUCT</a>, Thanks :smiley:'
          
      - name: Congratulate on every PR merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{tojson(github.event.number)}}
          body: |
            @${{ github.event.pull_request.user.login }} Hurray, your PR got merged 🥳. Thanks a bunch. Feel free to take another Issue.💖
